# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RAFCON
email: rafcon@dlr.de
description: "Develop your robotic tasks using an intuitive graphical user interface"
baseurl: "" #"/pages/common/rafcon" # the subpath of your site, e.g. /blog
url: https://dlr-rm.github.io/RAFCON # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  DLR-RM
repository: DLR-RM/RAFCON


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

# permalink: /:year/:month/:title.html
permalink: :year-:month-:title.html
sass:
    sass_dir: _sass
#    style: :compressed

logo: images/logos/rafcon-logo-standalone.png
google_site_verification: If_sNTkDtU-3NIeoc9M8Oaae6-uke5CtWlV-kHVmnhM