TYPE: DESIGN_CONFIG
USE_CUSTOM_DESIGN: False
FONTS_FOLDER: $RELATIVE_PATH{../../../share/fonts}
PRIMARY_FONT: "Quaerite Regnum Dei"
THEMES_FOLDER: $RELATIVE_PATH{../../../share/themes}
THEME_NAME: RAFCON
SOURCE_VIEW_FOLDER: $RELATIVE_PATH{../../../share/gtksourceview-3.0}
# overwrites gui_config.SOURCE_EDITOR_STYLE
SOURCE_VIEW_THEME: rafcon-agile
ICONS_FOLDER: $RELATIVE_PATH{../../../share/icons}
SPLASH_SCREEN_FOLDER: $RELATIVE_PATH{assets/splashscreens}
SPLASH_SCREEN_RESOLUTION_WIDTH: 800
SPLASH_SCREEN_RESOLUTION_HEIGHT: 560
SPLASH_SCREEN_HORIZONTAL_SPACING: 0
SPLASH_SCREEN_LABEL_HEIGHT: 100
SPLASH_SCREEN_SHOW_TEXT: False