TYPE: GUI_CONFIG

SOURCE_EDITOR_STYLE: rafcon-dark

GAPHAS_EDITOR_AUTO_FOCUS_OF_ROOT_STATE: True
ENABLE_CACHING: True
THEME_DARK_VARIANT: True
DRAG_N_DROP_WITH_FOCUS: False

PORT_SNAP_DISTANCE: 5

LOGGING_SHOW_VERBOSE: False
LOGGING_SHOW_DEBUG: False
LOGGING_SHOW_INFO: True
LOGGING_SHOW_WARNING: True
LOGGING_SHOW_ERROR: True
LOGGING_SHOW_POPUP: True
CONSOLE_FOLLOW_LOGGING: True

LIBRARY_TREE_PATH_HUMAN_READABLE: False
SUBSTITUTE_STATE_KEEPS_STATE_NAME: True

MINIMUM_SIZE_FOR_CONTENT: 30
MAX_VISIBLE_LIBRARY_HIERARCHY: 2
NO_FULLY_RECURSIVE_LIBRARY_MODEL: True

USE_ICONS_AS_TAB_LABELS: True

SHOW_NAMES_ON_DATA_FLOWS: True
SHOW_CONTENT_LIBRARY_NAME_TRANSPARENCY: 0.5
ROTATE_NAMES_ON_CONNECTIONS: False

HISTORY_ENABLED: True

KEEP_ONLY_STICKY_STATES_OPEN: True

AUTO_BACKUP_ENABLED: True
AUTO_BACKUP_ONLY_FIX_FORCED_INTERVAL: False
AUTO_BACKUP_FORCED_STORAGE_INTERVAL: 120
AUTO_BACKUP_DYNAMIC_STORAGE_INTERVAL: 20
AUTO_RECOVERY_CHECK: False
AUTO_RECOVERY_LOCK_ENABLED: False

SESSION_RESTORE_ENABLED: True

NUMBER_OF_RECENT_OPENED_STATE_MACHINES_STORED: 20

AUTO_APPLY_SOURCE_CODE_CHANGES: True

CHECK_PYTHON_FILES_WITH_PYLINT: False

DEFAULT_EXTERNAL_EDITOR:
PREFER_EXTERNAL_EDITOR: False

RESTORE_UNDOCKED_SIDEBARS: True

FULLSCREEN_SHOW_TOOLBAR: True

NOTIFICATIONS_MINIMUM_LOG_LEVEL: 50
NOTIFICATIONS_DURATION: 3

STATE_SELECTION_INSIDE_LIBRARY_STATE_ENABLED: True
LIBRARY_TREE_TOOLTIP_INCLUDES_ROOT_STATE_DESCRIPTION: True

ZOOM_WITH_CTRL: False

SEMANTIC_DATA_MODE: False
SHOW_PATH_NAMES_IN_EXECUTION_HISTORY: False
EXECUTION_TICKER_ENABLED: True
EXECUTION_TICKER_PATH_DEPTH: 3

# 300 is equal to glib.PRIORITY_LOW which is is lower than the default gtk priority
LOGGING_CONSOLE_GTK_PRIORITY: 300

SHORTCUTS:
    abort: Escape
    add: <Control>A
    add_execution_state: <Control><Alt>E
    add_hierarchy_state:
        - <Control><Alt>H
        - <Control><Shift>A
    add_preemptive_state: <Control><Alt>C
    add_barrier_state: <Control><Alt>B
    add_output: <Control><Alt>U
    add_input: <Control><Alt>N
    add_outcome: <Control><Alt>O
    add_scoped_variable: <Control><Alt>V
    apply: <Control><Shift>E
    backward_step: F9
    close: <Control>W
    copy: <Control>C
    cut: <Control>X
    data_flow_mode: <Control><Shift>D
    delete: Delete
    down:
        - <Control>Down
        - <Control><Shift>Down
    fit: <Control>space
    group: <Control>G
    info: <Control>I
    is_start_state:
        - <Control>E
        - <Control><Shift>X
    transition_from_closest_sibling_state: <Control><Shift>C
    transition_to_closest_sibling_state: <Control><Shift>V
    transition_to_parent_state: <Control><Shift>B
    left:
        - <Control>Left
        - <Control><Shift>Left
    new: <Control>N
    open: <Control>O
    open_external_editor: <Control><Shift>Q
    open_library_state_separately: <Control><Shift>space
    paste: <Control>V
    pause: F7
    quit: <Control>Q
    redo:
        - <Control>Y
        - <Control><Shift>Z
    reload: <Shift>F5
    rename: F2
    right:
        - <Control>Right
        - <Control><Shift>Right
    run_to_selected: <Control><Shift>R
    save: <Control>S
    save_as: <Control><Shift>S
    save_as_copy: <Control><Shift><Alt>S
    save_state_as: <Control><Alt>S
    substitute_state: <Control><Shift><Alt>U
    show_aborted_preempted: <Control>P
    show_data_flows: <Control>D
    show_transitions: <Control>T
    show_data_values: <Control>L
    start: F5
    start_from_selected: <Control>R
    run_selected: <Control><Shift>I
    only_run_selected: <Control><Shift>K
    step: F4
    step_mode: F6
    stop: F8
    undo: <Control>Z
    ungroup:
        - <Control><Shift>G
        - <Control>U
    up:
        - <Control>Up
        - <Control><Shift>Up
    fullscreen: F11
    search: <Control>F

SHOW_DIALOGS_DURING_RENAMING: false
MAX_LOGGING_BUFFER_LINES: 5000
