ENABLED: true
BURST_NUMBER: 1
CLIENT_UDP_PORT: 7777
HASH_LENGTH: 8
HISTORY_LENGTH: 1000
MAX_TIME_WAITING_FOR_ACKNOWLEDGEMENTS: 1.0
MAX_TIME_WAITING_BETWEEN_CONNECTION_TRY_OUTS: 3.0
SALT_LENGTH: 6
SERVER_IP: 127.0.0.1
SERVER_UDP_PORT: 9999
TIME_BETWEEN_BURSTS: 0.01
SERVER: false
TYPE: NETWORK_CONFIG
